title: Terry's Blog
description: Hi, this is Terry. I'm documenting my product thoughts and learning notes in this blog. I'm interested in creating new user experiences through generative ai, focusing on intuitive content generation and actionable insight extraction. Feel free to reach me at terrychen2026@u.northwestern.edu
url: "https://terrylinhaochen.github.io"
github_username: terrylinhaochen
linkedin_username: terry-chen-3b44911a4
collections:
  projects:
    output: true
baseurl: ""

