title: Terry's Blog
description: Hi, this is Terry. I'm documenting my product ideas and learning notes in this blog. I'm interested in llm generation synthesis and data insights through content understanding across text, image, and audio. Feel free to reach me at terrychen2026@u.northwestern.edu
url: "https://terrylinhaochen.github.io"
github_username: terrylinhaochen