title: Terry's Blog
description: Hi, this is Terry. I'm documenting my product thoughts and learning notes in this blog. I'm interested in creating new user experiences through generative ai, especially with regard to controlled content generation and insight extraction from multi-modal data. Feel free to reach me at terrychen2026@u.northwestern.edu
url: "https://terrylinhaochen.github.io"
github_username: terrylinhaochen