baseURL = "https://chenterry.com/"
languageCode = "en-us"
title = "Terry Chen"
theme = "PaperMod"
publishDir = "docs"
googleAnalytics = "G-M6GS8Q702L"

# Enhanced SEO description
description = "Terry Chen - AI Product Engineer & Investor. Exploring AI research, multi-agent systems, content understanding, and investment opportunities in emerging technologies."

# Enable sitemap and robots.txt
enableRobotsTXT = true

# SEO-specific configuration
[params.seo]
  # Default meta description
  defaultDescription = "Terry Chen - AI Product Engineer & Investor. Exploring AI research, multi-agent systems, content understanding, and investment opportunities in emerging technologies."
  
  # Default keywords
  defaultKeywords = ["AI", "Machine Learning", "Product Engineering", "Investment Analysis", "Multi-Agent Systems", "Content Understanding", "Emerging Technologies", "Startup Analysis"]
  
  # Social media settings
  [params.seo.social]
    twitterSite = "@terrychen_ai"
    twitterCreator = "@terrychen_ai"
    facebookAppId = ""
    
  # Schema.org settings
  [params.seo.schema]
    organizationName = "Terry Chen"
    organizationLogo = "https://chenterry.com/images/profile.jpg"
    organizationUrl = "https://chenterry.com"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Hi, this is Terry. I'm documenting my product ideas and learning notes in this blog. I'm interested in creating new user experiences through generative ai, focusing on synthesized content generation and actionable insight extraction."
  author = "Terry Chen"
  env = "production"
  
  # SEO-specific params
  images = ["/images/profile.jpg"] # Default social share image
  keywords = ["AI", "Machine Learning", "Product Engineering", "Investment Analysis", "Multi-Agent Systems", "Content Understanding", "Emerging Technologies", "Startup Analysis", "AI Multipliers"]
  
  # Default OpenGraph and Twitter card settings
  [params.twitter]
    site = "@terrychen_ai"
    creator = "@terrychen_ai"
    card = "summary_large_image"
  
  # Main sections to include in lists and archives
  mainSections = ["posts"]
  
  # PaperMod specific parameters
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowFullTextinRSS = true
  
  # Home page info
  [params.homeInfoParams]
    Title = "👋 Welcome to Terry's Blog"
    Content = "Hi, this is Terry. I work as an SEO Product Engineer focused on AI Multipliers to enhance content generation and insight extraction. I'm documenting my product ideas and learning notes in this blog. You can reach me at terrychen2026@u.northwestern.edu"
  
  # Enable searching
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

  # Social links
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/terry-chen-3b44911a4/"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/terrylinhaochen"
  [[params.socialIcons]]
    name = "threads"
    url = "https://www.threads.com/@terry_clh?igshid=NTc4MTIwNjQ2YQ=="
  [[params.socialIcons]]
    name = "twitter"
    url = "https://x.com/227terry?s=21"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:terrychen2026@u.northwestern.edu"

  # Assets for cover images and profile pictures
  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
    
# Menu items
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "product"
    name = "Product"
    url = "/product/"
    weight = 20
  [[menu.main]]
    identifier = "investing"
    name = "Investing"
    url = "/investing/"
    weight = 25
  # Archived section removed from main navigation
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30
      
# Taxonomies for categorization
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Enable search
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

# Image handling
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Make sure this is set to true to allow HTML in markdown 