#!/usr/bin/env python3
"""Sync the book catalog from Readwise highlights to the site.

Privacy model (deliberate, do not loosen):
  - Queries ONLY category=books. Articles, tweets, and podcasts — where
    highlights about people and current reading live — are never requested.
  - Syncs ONLY metadata: title, author, cover URL, highlight count.
    Highlight text never leaves Readwise.
  - Titles listed under `readwise_exclude:` in data/books.yaml are skipped.

Classification: >= 3 highlights -> read ("Off the Shelf"); fewer -> shelf.
Books already curated by hand in data/books.yaml are skipped (loose title
match), so hand-written notes always win over the automated entry.

Usage:
    READWISE_TOKEN=... python3 scripts/sync_readwise_books.py

Output: data/readwise_books.json, rendered by layouts/reading/list.html.
Run on a schedule by .github/workflows/sync-books.yml. Stdlib only.
"""

import json
import os
import re
import sys
import time
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOOKS_YAML = os.path.join(ROOT, "data", "books.yaml")
OUTPUT = os.path.join(ROOT, "data", "readwise_books.json")
READ_THRESHOLD = 3


def norm(title):
    t = re.sub(r"[^a-z0-9一-鿿 ]", "", (title or "").lower())
    return " ".join(t.split()[:4]) if " " in t.strip() else t.strip()


def load_catalog_state():
    """Return (set of normalized titles already curated, set of excluded titles)."""
    text = open(BOOKS_YAML, encoding="utf-8").read()
    curated = {norm(m) for m in re.findall(r'^\s+- title:\s*"(.+)"', text, re.M)}
    excluded = set()
    block = re.search(r"^readwise_exclude:\n((?:\s+-\s+.*\n?)+)", text, re.M)
    if block:
        excluded = {norm(m.strip().strip('"')) for m in re.findall(r"-\s+(.+)", block.group(1))}
    return curated, excluded


def fetch_books(token):
    books, url = [], "https://readwise.io/api/v2/books/?category=books&page_size=1000"
    while url:
        req = urllib.request.Request(url, headers={"Authorization": f"Token {token}"})
        with urllib.request.urlopen(req, timeout=30) as r:
            data = json.load(r)
        books += data["results"]
        url = data.get("next")
        if url:
            time.sleep(0.5)
    return books


def main():
    token = os.environ.get("READWISE_TOKEN", "")
    if not token:
        print("error: set READWISE_TOKEN", file=sys.stderr)
        return 1

    curated, excluded = load_catalog_state()
    read, shelf, skipped = [], [], 0
    for b in fetch_books(token):
        key = norm(b["title"])
        if not key or b["num_highlights"] == 0 or key in excluded or key in curated:
            skipped += 1
            continue
        cover = b.get("cover_image_url") or ""
        if "default-book-icon" in cover:
            cover = ""  # site's styled text fallback beats Readwise's gray placeholder
        entry = {
            "title": b["title"],
            "author": b.get("author") or "",
            "cover": cover,
            "highlights": b["num_highlights"],
        }
        (read if b["num_highlights"] >= READ_THRESHOLD else shelf).append(entry)

    read.sort(key=lambda x: -x["highlights"])
    shelf.sort(key=lambda x: -x["highlights"])

    payload = {
        "_comment": "AUTO-GENERATED by scripts/sync_readwise_books.py from Readwise (category=books only; metadata only, never highlight text). Manual edits will be overwritten. To hide a title, add it to readwise_exclude in data/books.yaml; to add notes, move it into books.yaml.",
        "read": read,
        "shelf": shelf,
    }
    output = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    old = open(OUTPUT, encoding="utf-8").read() if os.path.exists(OUTPUT) else ""
    if output == old:
        print(f"no changes ({len(read)} read, {len(shelf)} shelf, {skipped} skipped)")
        return 0
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(output)
    print(f"wrote {OUTPUT}: {len(read)} read, {len(shelf)} shelf, {skipped} skipped")
    return 0


if __name__ == "__main__":
    sys.exit(main())
