#!/usr/bin/env python3
"""Sync approved book recommendations from a Google Sheet to the site.

Pipeline:
  1. Visitors submit a Google Form ("Recommend a book to Terry").
  2. The form feeds a Google Sheet. You add an extra column named "Approved"
     (Insert > Checkbox) and tick it for recommendations you want published.
  3. Publish that sheet tab as CSV: File > Share > Publish to web >
     (pick the responses tab, select "Comma-separated values (.csv)") and
     copy the URL.
  4. This script fetches the CSV, keeps only approved rows, and writes
     data/book_recommendations.json, which the /reading/ page renders.

Usage:
    python3 scripts/sync_book_recommendations.py            # uses $BOOKS_SHEET_CSV_URL
    python3 scripts/sync_book_recommendations.py <csv_url>  # explicit URL

Run by .github/workflows/sync-books.yml on a schedule, so ticking the
checkbox is all that's needed — the site updates automatically.

No third-party dependencies (stdlib only).
"""

import csv
import io
import json
import os
import sys
import urllib.request

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "book_recommendations.json")

# Header detection: first matching substring (case-insensitive) wins.
FIELD_ALIASES = {
    "title": ["title", "book"],
    "author": ["author"],
    "note": ["why", "reason", "recommend because", "anything you want to say"],
    "recommended_by": ["your name", "name"],
    "isbn": ["isbn"],
    "approved": ["approved", "approve"],
    "timestamp": ["timestamp"],
}

TRUTHY = {"true", "yes", "y", "1", "checked", "x"}


def map_headers(headers):
    mapping = {}
    for field, aliases in FIELD_ALIASES.items():
        for i, header in enumerate(headers):
            h = header.strip().lower()
            if any(alias in h for alias in aliases) and i not in mapping.values():
                mapping[field] = i
                break
    return mapping


def fetch_csv(url):
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read().decode("utf-8-sig")


def main():
    url = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("BOOKS_SHEET_CSV_URL", "")
    if not url:
        print("error: pass the published-CSV URL as an argument or set BOOKS_SHEET_CSV_URL", file=sys.stderr)
        return 1

    rows = list(csv.reader(io.StringIO(fetch_csv(url))))
    if not rows:
        print("error: sheet is empty", file=sys.stderr)
        return 1

    mapping = map_headers(rows[0])
    if "title" not in mapping:
        print(f"error: could not find a Title column in headers: {rows[0]}", file=sys.stderr)
        return 1
    if "approved" not in mapping:
        print("error: no 'Approved' column found — add a checkbox column named 'Approved' to the sheet", file=sys.stderr)
        return 1

    def cell(row, field):
        idx = mapping.get(field)
        return row[idx].strip() if idx is not None and idx < len(row) else ""

    recommendations = []
    total = 0
    for row in rows[1:]:
        if not cell(row, "title"):
            continue
        total += 1
        if cell(row, "approved").lower() not in TRUTHY:
            continue
        rec = {
            "title": cell(row, "title"),
            "author": cell(row, "author"),
            "recommended_by": cell(row, "recommended_by"),
            "note": cell(row, "note"),
        }
        isbn = cell(row, "isbn").replace("-", "").replace(" ", "")
        if isbn:
            rec["isbn"] = isbn
        recommendations.append(rec)

    payload = {
        "_comment": "AUTO-GENERATED by scripts/sync_book_recommendations.py from the Google Sheet behind the recommendation form. Only rows with the 'Approved' checkbox ticked land here. Manual edits will be overwritten on the next sync.",
        "recommendations": recommendations,
    }

    output = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    out_path = os.path.normpath(OUTPUT_PATH)
    old = open(out_path, encoding="utf-8").read() if os.path.exists(out_path) else ""
    if output == old:
        print(f"no changes ({len(recommendations)}/{total} submissions approved)")
        return 0

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(output)
    print(f"wrote {out_path}: {len(recommendations)}/{total} submissions approved")
    return 0


if __name__ == "__main__":
    sys.exit(main())
